### ISSUE TITLE
Link component inside a Tab causes error

### ISSUE THREAD

**Issue by burlakko** [hupe1980/gatsby-theme-material-ui#42] opened 2020-06-16 04:50 UTC
When using the theme's Link component as a Material-ui Tab got an error 'Failed prop type: Invalid prop `component` supplied to `ForwardRef(ButtonBase)`. Expected an element type that can hold a ref. Did you accidentally provide a plain function component instead?'

```
import Tab from '@material-ui/core/Tab'
import { Link } from 'gatsby-theme-material-ui'
<Tab  component={Link} to="link-url" label="Link label" />
```

**Comment by rejas** [comment] 2020-07-20 12:19
Got this too when using a Link as the component of a ListItem like this:

```
import { Link } from 'gatsby-theme-material-ui';
import { ListItem } from '@material-ui/core';

            <ListItem
              button
              key={post.id}
              component={Link}
              to={post.fields.slug}
            >
```

Got 
```
Warning: Failed prop type: Invalid prop `component` supplied to `ForwardRef(ButtonBase)`. Expected an element type that can hold a ref. Did you accidentally provide a plain function component instead? For more information see https://material-ui.com/r/caveat-with-refs-guide
```
and
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```
in my console ...

**Comment by oliviertassinari** [comment] 2020-07-20 14:32
@rejas Thanks for the feedback. The solution https://github.com/hupe1980/gatsby-theme-material-ui/issues/30#issuecomment-623603772.

**Comment by rejas** [comment] 2020-07-20 19:16
@oliviertassinari you mean I need to patch the library myself or how do I interpret that comment there?

**Comment by oliviertassinari** [comment] 2020-07-20 19:18
It means that we need to patch this package.

**Comment by rejas** [comment] 2020-07-20 19:18
That was quick :-) Any ETA or can I help out somehow?

**Comment by oliviertassinari** [comment] 2020-07-20 19:21
I'm not responsible for this package, however, I think that if you could make a pull request, it will help the author.

**Comment by hupe1980** [comment] 2020-07-20 19:23
@rejas You are welcome to create a PR

**Comment by rejas** [comment] 2020-07-20 19:36
I am not that good in typescript or in the deeper react internals to write one in a reasonable amount of time :-(

**Comment by rejas** [comment] 2020-07-21 09:31
Thx for doing the PR @hupe1980 Any ETA when it will be released?

**Comment by hupe1980** [comment] 2020-07-21 10:12
The changes have just been released

**Closed** 2020-07-21 10:13 UTC

**Comment by rejas** [comment] 2020-07-21 19:31
Thx, but do I have to do something besides updating to v1.0.11 in my package.json? Because I weirdly still get the errors....

**Comment by oliviertassinari** [comment] 2020-07-21 20:27
@rejas Do you have a reproduction?

**Comment by rejas** [comment] 2020-07-21 20:33
You can check my veeck rep here at github :-) Doing an npm install doesnt seem to fetch the changed file into my node_modules (rm -rf 'ed the whole thing twice to be sure)...

**Comment by hupe1980** [comment] 2020-07-21 20:34
@rejas You're right. ForwardRef was still missing in a second place:
https://github.com/hupe1980/gatsby-theme-material-ui/blob/98f96e301c508b019667840e4defefe697194f63/packages/gatsby-material-ui-components/src/link.tsx#L6

**Comment by hupe1980** [comment] 2020-07-21 20:38
@rejas Please try version gatsby-theme-material-ui@**1.0.12**

**Comment by rejas** [comment] 2020-07-22 05:48
@hupe1980 Perfect, all errors are gone!!
